### ISSUE TITLE
请教一下字体设置的问题

### ISSUE THREAD

**Issue by Akesaka-Hitsuki** [wowhxj/emacs-from-scratch#3]
尝试在wsl上使用emacs 按照教程配置到改变emacs样貌的那节
但是在安装完doom-modeline之后 我发现modeline上org图标右侧的保存图标显示为0F0CFB
在尝试过安装noto color emoji、安装all-the-icons并将安装的字体写入‘emoji设置中都没有解决
最后安装nerd-icons后将安装的nerd font写入'emoji设置后解决了这个问题
想请教一下 是否能用nerd font替代noto color emoji之类的emoji字体（

**Comment by wowhxj** [comment]
如果nerd font里包含有emoji的相关字符，那就可以的。具体我也没用过，你可以自己下载字体自己尝试，Emacs好玩的地方就是不断的尝试，不断的寻找问题的答案。我用的emoji字体是 `Noto Emoji`。
```emacs-lisp
;; set emoji font
  (set-fontset-font
   t
   (if (version< emacs-version "28.1")
       '(#x1f300 . #x1fad0)
     'emoji)
   (cond
    ((member "Noto Emoji" (font-family-list)) "Noto Emoji")
    ((member "Symbola" (font-family-list)) "Symbola")
    ((member "Apple Color Emoji" (font-family-list)) "Apple Color Emoji")
    ((member "Noto Color Emoji" (font-family-list)) "Noto Color Emoji")
    ((member "Segoe UI Emoji" (font-family-list)) "Segoe UI Emoji")
    ))
```

**Comment by Akesaka-Hitsuki** [comment]
👌
我又去看了一下nerd-icons的readme
在保持你原本教程emoji这部分设置的情况下 不需要将nerd font添加到emoji部分
直接
```emacs-lisp
(use-package nerd-icons
  :ensure t
  :custom
  (nerd-icons-font-family "Symbols Nerd Font Mono") ;;该字体为nerd-icons默认字体 可以自行替换
)
```
这样就能保证图标显示正确了

**Comment by Akesaka-Hitsuki** [comment]
研究了一番 发现最大的问题是我把all-the-icons下的字体放在了emoji设置的前面
然后下noto color emoji的时候一通操作又禁用了symbola 导致各种问题
现在注释掉了禁用symbola的那段 用symbola终于一切正常了
😔
