### ISSUE TITLE
consult部分的设置问题

### ISSUE THREAD

**Issue by Akesaka-Hitsuki** [wowhxj/emacs-from-scratch#4]
在复制了consult部分的配置之后
我发现当我使用`C-x b`(也就是cosult-buffer)后 提示我`[134217774] is not a valid key definition; see 'key-valid-p'`
研究一番没找到解决方案后尝试使用其他命令
- 使用`M-x consult-buffer-other-window`和`M-x consult-buffer-other-frame`提示同样的错误
- 使用`C-c g`和`M-x consult-repgrip`  提示 `Wrong type argument: overlayp, nil`

最后参照了consult的[issue698](https://github.com/minad/consult/issues/698)之后将
```emacs-lisp
 :config
  (consult-customize
   consult-theme
   :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-recent-file consult--source-project-recent-file consult--source-bookmark
   :preview-key (kbd "M-."))
```
这部分注释掉之后 这些尝试过的快捷键都能用了
不清楚具体原因 仅供参考

**Comment by wowhxj** [comment]
是的，插件一直在变化，有的变化可能会改一些函数名，或直接相关函数直接改掉了，我有一段时间没有更新插件了，晚些时候我会用最新的插件来修复一下相关的配置文件。感谢支持！

**Comment by wowhxj** [comment]
最新的一课：34. Emacs更新插件，我修复了这个问题，也说明了方法。先close掉了。
